version: '3.1'

services:
  aplicacionjava:
    image: tomcat:9.0
    restart: always
    volumes:
      - ./sample.war:/usr/local/tomcat/webapps/sample.war:ro
    networks:
      - app-net

  proxy:
    image: nginx
    restart: always
    ports:
      - "1024:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-net
    depends_on:
      - aplicacionjava

networks:
  app-net:
